controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

product_list:
    path: /products
    controller: App\Controller\ProductController::list

product_show:
    path: /{code}
    controller: App\Controller\ProductController::show
    requirements:
        id: '\d+'
        slug: '[a-zA-Z0-9-]+'
    methods: [GET]

product_index:
    path: /product/index
    controller: App\Controller\ProductController::productReference

category_filter:
    path: /category/filter
    controller: App\Controller\CategoryController::filter

category_no_filter:
    path: /category/no-filter
    controller: App\Controller\CategoryController::noFilter
